# Google App Engine configuration for AbacusHub
runtime: nodejs20

# Environment variables
env_variables:
  NODE_ENV: production
  NEXTAUTH_URL: https://clineapi-460920.uc.r.appspot.com
  NEXTAUTH_SECRET: zZNf6KYt+L20VNPSfsBnlLhaX44GL7tFuvDc12HWwYo=
  DATABASE_URL: file:./prisma/prod.db
  MAX_FILE_SIZE: "524288000"
  MAX_CHUNK_SIZE: "5242880"
  MIN_CHUNK_SIZE: "1048576"
  STORAGE_TYPE: local
  RATE_LIMIT_REQUESTS: "1000"
  RATE_LIMIT_WINDOW: "60000"
  E2E_TESTING: "false"
  DISABLE_SSE_RATE_LIMITING: "false"

# Scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.7

# Resource allocation
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Network settings
network:
  session_affinity: false

# Health checks
readiness_check:
  path: "/api/debug/simple"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/api/debug/simple"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# File upload limits and static file handling
handlers:
  # Next.js build-specific static assets (build manifests)
  - url: /_next/static/appflowy-v2-stable
    static_dir: .next/static/appflowy-v2-stable
    secure: always
    expiration: 365d
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"
      
  # Next.js static chunks - critical for AppFlowy design hydration
  - url: /_next/static/chunks
    static_dir: .next/static/chunks
    secure: always
    expiration: 365d
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"
      
  # Next.js static CSS - critical for AppFlowy design styles
  - url: /_next/static/css
    static_dir: .next/static/css
    secure: always
    expiration: 365d
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"
      
  # Next.js static media (fonts, images)
  - url: /_next/static/media
    static_dir: .next/static/media
    secure: always
    expiration: 365d
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"
      
  # All other Next.js static assets
  - url: /_next/static
    static_dir: .next/static
    secure: always
    expiration: 365d
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"
  
  # Public files
  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico
    secure: always
    
  # All other routes handled by Next.js
  - url: /.*
    script: auto
    secure: always

# Standard Next.js entrypoint (not standalone)
entrypoint: npm start

# Cloud SQL connection - disabled for SQLite deployment
# beta_settings:
#   cloud_sql_instances: clineapi-460920:us-central1:abacushub-db

# VPC access (if needed for private resources)
# vpc_access_connector:
#   name: projects/YOUR-PROJECT-ID/locations/REGION/connectors/CONNECTOR-NAME

# Custom runtime settings
runtime_config:
  operating_system: ubuntu22
  runtime_version: 20